### PR TITLE
Bug fixes aligned to logged issues

### LINKED ISSUE #204: Bug Report: Private DNS zone link in setting.connectivity.tf
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:  1.0.10

**azure provider**: 2.82.0

**module**:   1.0

### Description

In setting.connectivity.tf file the Private DNS zone are linked to the VNET's even when the bellow boolean's were false. this happens for the hub vnet and for the spoke vnet 

          enable_private_dns_zone_virtual_network_link_on_hubs   = false
          enable_private_dns_zone_virtual_network_link_on_spokes = false

**Steps to Reproduce**

1. Create hub vnet and attach the spoke vnet (spoke_virtual_network_resource_ids)  in the setting.connectivity.tf
2. put the following values to false:
          enable_private_dns_zone_virtual_network_link_on_hubs   = false
          enable_private_dns_zone_virtual_network_link_on_spokes = false

3. in the TF plan the link between VNET and private DNS zone is created.

### LINKED ISSUE #216: Incorrect `enforcementMode` setting on `Enable-DDoS-VNET` Policy Assignment
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: `v1.0.11`

**azure provider**: `v2.86.0`

**module**: `v1.0.0`

### Description

**Describe the bug**

The `Enable-DDoS-VNET` Policy Assignment on the `${local.root_id}-landing-zones` Management Group is being enforced regardless of whether `configure_connectivity_resources.settings.ddos_protection_plan.enabled` is set to `true` or `false`.

**Steps to Reproduce**

1. Create an ES configuration where:
    1. `deploy_connectivity_resources` is set to `true`
    2. `configure_connectivity_resources.settings.ddos_protection_plan.enabled` is set to `false`
    3. `subscription_id_connectivity` is set to a valid Subscription ID (also map to the `azurerm.connectivity` provider
    4. Associate a test "Application Workload" Subscription to any Management Group under the scope of the `${local.root_id}-landing-zones` Management Group
2. Deploy the configuration
3. Try to create a new Virtual Network in the "Application Workload" Subscription
4. Validate the error message as below, indicating that the `Modify` effect is being enforced
5. Also note that the `ddosPlan` value for parameters on this assignment hasn't been updated

```shell
╷
│ Error: creating/updating Virtual Network: (Name "tfes-acc-vnet-northeurope" / Resource Group "tfes-acc-connectivity-northeurope"): network.VirtualNetworksClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client has permission to perform action 'Microsoft.Network/ddosProtectionPlans/join/action' on scope '/subscriptions/5cd8150d-505d-4bc4-bb0f-8b2311439f48/resourceGroups/tfes-acc-connectivity-northeurope/providers/Microsoft.Network/virtualNetworks/tfes-acc-vnet-northeurope', however the linked subscription '00000000-0000-0000-0000-000000000000' was not found. "
│
│   with azurerm_virtual_network.app000001,
│   on spokes.tf line 30, in resource "azurerm_virtual_network" "app000001":
│   30: resource "azurerm_virtual_network" "app000001" {
│
╵
```

**Screenshots**

Terraform failure:

image

Policy Assignment configuration in Terraform state:

image

**Additional context**

### PR DESCRIPTION
**Pull request by krowlandson**
## Overview/Summary

Replace this with a brief description of what this Pull Request fixes, changes, etc.

## This PR fixes/adds/changes/removes

1. Update boolean logic controlling deployment of `azurerm_private_dns_zone_virtual_network_link` resources (fixes #204)
2. Added parameter configuration in `connectivity` module to correctly configure `Enable-DDoS-VNET` Policy Assignment at `landing-zones` scope (fixes #216)

### Breaking Changes

none

### #204

evidence-fix-204

evidence-fix-204-2

### #216 

evidence-fix-216

evidence-fix-216-apply

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.
- [x] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located in the [Enterprise-Scale repo](https://github.com/Azure/Enterprise-Scale) in the directory: `/docs/wiki/whats-new.md`)

### CODE REVIEW

**Review by jtracey93 — CHANGES_REQUESTED** [review]
Looks good. 

Can you upload the evidence for #204 to the PR though please? @krowlandson

**Comment by krowlandson** [comment]
Evidence attached

**Review by jtracey93 — APPROVED** [review]
Thanks for the evidence 👍 

Looks good, just running E2Es

**Pull request merged**
