### PR TITLE
Network gateway default parameters

### PR DESCRIPTION
**Pull request by chrsundermann**
## Overview/Summary

This is the Pull Request for the issue #924. 

## This PR fixes/adds/changes/removes

1. adds azurerm_virtual_network_gateway attribute, remote_vnet_traffic_enabled
2. adds azurerm_virtual_network_gateway attribute, virtual_wan_traffic_enabled

### Breaking Changes

1.  Attributes were implemented with >= 3.84.0 of the azurerm provider

## Testing Evidence

Terraform plan before changes:

image

Terraform plan after changes shows "Nothing to change".

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main)
- [x] Performed testing and provided evidence.
- [ ] Updated relevant and associated documentation.

### CODE REVIEW

**Comment by chrsundermann** [comment]
@microsoft-github-policy-service agree [company="adesso SE"]

**Comment by chrsundermann** [comment]
@microsoft-github-policy-service agree

**Comment by matt-FFFFFF** [comment]
Hi @chrsundermann please can you run `terraform fmt -recursive` and commit the changes?

**Comment by chrsundermann** [comment]
> Hi @chrsundermann please can you run `terraform fmt -recursive` and commit the changes?

Hi @matt-FFFFFF, I executed `terraform fmt -recursive` and pushed the changes.

**Comment by chrsundermann** [comment]
Hi @matt-FFFFFF,
do you have any updates on this cause I can't look into the AZ pipelines errors.

**Comment by matt-FFFFFF** [comment]
Minimum provider versions. Also there's a mapping missing as the data traverses through the module somewhere too

**Comment by matt-FFFFFF** [comment]
Thanks for this - I've pulled into the ama branch for the next major release

**Comment by matt-FFFFFF** [comment]
@chrsundermann I had to add null values to the corresponding VPN gateway object in order for the values to be preserved when they are `concat()`

```terraform
  azurerm_virtual_network_gateway_vpn = [
    for location, hub_network in local.hub_networks_by_location :
    {
      # ...
      remote_vnet_traffic_enabled = null
      virtual_wan_traffic_enabled = null
```

**Comment by chrsundermann** [comment]
Thanks for the update @matt-FFFFFF. Could only check with ExpressRoute setup. This was successfully deployed at customer site.

**Comment by matt-FFFFFF** [comment]
I don't think the attributes are valid for VPN but since all list members have to have same schema, needed to add as nulls.

**Pull request merged**
