### PR TITLE
Add VWAN deployment capability

### LINKED ISSUE #226: Add capability for "Virtual WAN Networking" resources - Connectivity Subscription
To improve alignment with the ARM reference implementation option, this issue outlines the requirement to add support for deploying an [Azure Virtual WAN](https://docs.microsoft.com/en-us/azure/virtual-wan/virtual-wan-about) based `hub` as part of the `connectivity` capability.

This would align to the [Contoso reference architecture](https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/contoso/Readme.md), providing the option to easily scale to support multiple Azure regions and on-premises locations (any-to-any connectivity) as shown in the following figure:

Azure landing zones Contoso networking diagram

The `connectivity` child module already has a placeholder for this capability to be added without making a breaking change to the module:

```hcl
{
  settings = {
    hub_networks = [
      # (hub_network instance(s) hidden)
    ]
    vwan_hub_networks = [
      # (Placeholder for vwan_hub_networks instance(s) to be added)
    ]
    ddos_protection_plan = {
      # (child elements hidden)
    }
    dns = {
      # (child elements hidden)
    }
  }
  location = null
  tags     = null
  advanced = null
}
```

Need to agree on the resource to be deployed, and configuration schema used to control settings (aligned to that already being used for `hub_networks = []`

### LINKED ISSUE #271: Error: deleting Azure Firewall
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: `Terraform v1.1.5`

**azure provider**: `+ provider registry.terraform.io/hashicorp/azurerm v2.83.0`

**module**: `v1.1.2`

### Description

**Describe the bug**

When running `terraform destroy` with a configuration which has deployed one or more Azure Firewall resources, we get the following error:

```shell
╷
│ Error: deleting Azure Firewall Firewall: (Azure Firewall Name "12345-fw-northeurope" / Resource Group "12345-connectivity-northeurope") : network.AzureFirewallsClient#Delete: Failure sending request: StatusCode=415 -- Original Error: Code="UnsupportedMediaType" Message="The content media type '<null>' is not supported. Only 'application/json' is supported."
│
│
╵
```

This results in multiple resources failing to be destroyed due to dependencies.

**Steps to Reproduce**

1. Create a module configuration which deploys at least 1 virtual network using `hub_networks` or `vwan_hub_networks` with the Azure Firewall enabled.
2. Run `terraform apply` and confirm.
3. Once deployment is completed, run `terraform destroy` and confirm.
4. Take note of the error message and resources which are still to be destroyed.

**Screenshots**

image

**Additional context**

This appears to be an Azure API related breaking change which has impacted multiple 3rd party tooling, including the Azure provider for Terraform.

Please refer to the following issue for reference:

- https://github.com/hashicorp/terraform-provider-azurerm/issues/14966

> **NOTE**: This issue is fixed in [v2.96.0 of the Terraform Provider](https://github.com/hashicorp/terraform-provider-azurerm/blob/v2.96.0/CHANGELOG.md).

### LINKED ISSUE #272: Argument `management_group_name` deprecated in favour of `management_group_id`
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: `Terraform v1.1.5`

**azure provider**: `+ provider registry.terraform.io/hashicorp/azurerm v2.95.0` onwards

**module**: `v1.1.2`

### Description

**Describe the bug**

As of the release [v2.95.0 of the Terraform Provider](https://github.com/hashicorp/terraform-provider-azurerm/blob/v2.95.0/CHANGELOG.md), the following message is now being displayed:

```shell
╷
│ Warning: Argument is deprecated
│
│   with module.test_core.azurerm_policy_definition.enterprise_scale,
│   on ..\..\..\resources.policy_definitions.tf line 12, in resource "azurerm_policy_definition" "enterprise_scale":
│   12:   management_group_name = try(basename(each.value.scope_id), null)
│
│ Deprecated in favour of `management_group_id`
│
│ (and 111 more similar warnings elsewhere)
╵
```

**Steps to Reproduce**

1. Create any working implementation of the module which includes Policy Definitions, with the minimum `azurerm` provider version set to `2.95.0`
2. Run `terraform init -upgrade`
3. Run `terraform plan` or `terraform apply`
4. Take note of the error above

**Screenshots**

image

**Additional context**

### LINKED ISSUE #273: `azurerm_role_assignment.policy_assignment` resources outputs missing
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: `Terraform v1.1.5`

**azure provider**: `+ provider registry.terraform.io/hashicorp/azurerm v2.83.0`

**module**: `v1.1.2`

### Description

**Describe the bug**

When reviewing the outputs generated by the module, it has been noted that values for the `azurerm_role_assignment.policy_assignment` resources are missing.

**Steps to Reproduce**

1. Create a default implementation of the module, add include the following output:
```hcl
output "azurerm_role_assignment" {
  value = module.enterprise_scale.azurerm_role_assignment # Replace `enterprise_scale` with the name associated with your module block
}
```
2. Run `terraform apply`
3. Note that outputs are only included for `azurerm_role_assignment.enterprise_scale` and not `azurerm_role_assignment.policy_assignment`

**Screenshots**

n/a

**Additional context**

This is where the output is generated, showing only the `azurerm_role_assignment.enterprise_scale` resources included:

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/969fba693493f280513ccad31de5234beff622ec/outputs.tf#L51-L58

### PR DESCRIPTION
**Pull request by krowlandson**
## Overview/Summary

This PR adds VWAN deployment capability to the module, and updates the test framework to provide coverage for this.

Documentation is to follow, and there are a few areas which will be updated before the next release for both VWAN and H&S network topologies (e.g. adding support for firewall policy creation).

> Update to the What's New page in the ES wiki will be added upon release, not specifically for this PR

## This PR fixes/adds/changes/removes

1. Add resources for VWAN connectivity option to fix #226
2. Update test framework to include VWAN resources and implement the configuration in stages to better reflect a typical user journey for deploying and updating configuration settings
3. Partial coverage for #227
4. Update minimum supported version to fix #271
5. Fix #272
6. Fix #273

### Breaking Changes

1. Change to minimum supported provider version may require customers to update their code and run `terraform init -upgrade`

## Testing Evidence

_to follow_

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.
- [x] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located in the [Enterprise-Scale repo](https://github.com/Azure/Enterprise-Scale) in the directory: `/docs/wiki/whats-new.md`)

### CODE REVIEW

**Comment by matt-FFFFFF** [comment]
Looks great! Only comment is can we split locals.connectivity into smaller files to make reading easier? @krowlandson

**Comment by krowlandson** [comment]
> Looks great! Only comment is can we split locals.connectivity into smaller files to make reading easier? @krowlandson Kevin Rowlandson FTE

Do we need this now, or tackle as part of adding in all the extra logic to further remove `tr()` functions as per #227?

**Review by matt-FFFFFF — APPROVED** [review]
E2E changes working so :shipit:

**Comment by mlomat** [comment]
@krowlandson Do you have any documentation or example for Virtual Hub deployment? Or is it placeholder only for future use?

**Pull request merged**
