### PR TITLE
Fix multiple issues

### LINKED ISSUE #232: can't create active-active vpngw
### Versions
v1.1.0

**terraform**:
1.0.11

**azure provider**:
version = "~> 2.87"

**module**:

### Description

As we want an active-active VPN gw, we configure two public IPs in order to pass these as ip_configuration to the module:

```terraform

resource "azurerm_public_ip" "vpn_gw" {
  count               = 2
  allocation_method   = "Static"
  location            = var.default_location
  tags                = var.default_tags
  sku                 = "Standard"
  name                = "VpnGw${count.index}"
  resource_group_name = local.comms_resource_group_name
}

data "azurerm_subnet" "gateway_subnet" {
  name                 = "GatewaySubnet"
  resource_group_name  = local.comms_resource_group_name
  virtual_network_name = "es-hub-${var.default_location}"
}

...
 configure_connectivity_resources = {
    advanced = {
      custom_settings_by_resource_type = {
        azurerm_virtual_network_gateway = {
          connectivity = {
            vpngw = {
              (var.default_location) = {
                enable_bgp    = true
                active_active = true
                ip_configuration = [
                  {
                    name                          = "vnetGatewayConfig1"
                    public_ip_address_id          = azurerm_public_ip.vpn_gw[0].id
                    private_ip_address_allocation = "Dynamic"
                    subnet_id                     = data.azurerm_subnet.gateway_subnet.id
                  },
                  {
                    name                          = "vnetGatewayConfig2"
                    public_ip_address_id          = azurerm_public_ip.vpn_gw[1].id
                    private_ip_address_allocation = "Dynamic"
                    subnet_id                     = data.azurerm_subnet.gateway_subnet.id
                  }
                ]
              }
            }
          }
        }
      }
    }
```

But still the module will create a pip for the gateway, from `terraform plan`:
```terraform
  # module.caf-enterprise-scale.azurerm_public_ip.connectivity["/subscriptions/mySub/resourceGroups/es-connectivity-myLocation/providers/Microsoft.Network/publicIPAddresses/es-vpngw-myLocation-pip"] will be created
  + resource "azurerm_public_ip" "connectivity" {
      + allocation_method       = "Static"
      + availability_zone       = "Zone-Redundant"
      + fqdn                    = (known after apply)
      + id                      = (known after apply)
      + idle_timeout_in_minutes = 4
      + ip_address              = (known after apply)
      + ip_version              = "IPv4"
      + location                = "myLocation"
      + name                    = "es-vpngw-myLocation-pip"
      + resource_group_name     = "es-connectivity-myLocation"
      + sku                     = "Standard"
      + sku_tier                = "Regional"
      + tags                    = {
          + "deployedBy" = "terraform/azure/caf-enterprise-scale/v1.1.0"
          + "terraform"  = "true"
        }
      + zones                   = (known after apply)
    }
```

**Steps to Reproduce**

1. pass ip_configuration to the module
2. observe that ip_configuration is used, but still a pip (which won't be needed or used) is also created

**Screenshots**
N/A

**Additional context**
N/A

### LINKED ISSUE #309: Bug Report - AzureRM provider 3.0.0 availability zones error
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 0.15.0

**azure provider**: 3.0.0 and 3.0.1

**module**: 1.1.2

### Description

**Describe the bug**

Build validation fails with the following message...
image

This seems to be caused by the availability zones update in version 3.0.0 of the Azure RM provider which was released in the last 24 hours (https://www.hashicorp.com/blog/terraform-azurerm-3-0-brings-enhanced-azure-function-support).
 
**Steps to Reproduce**

1. Ensure provider version is not specified (this defaults to the latest 3.0.1).
2. Execute terraform init.
3. Execute terraform validate - this will throw the error message above.

**Screenshots**

Provided aboove.

**Additional context**

Explicitly specifying provider version 2.99.0 resolves the issue.

### LINKED ISSUE #319: `azurerm_public_ip` prevents support of azurerm provider >= 3.0.0
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: `any`

**azure provider**: `v3.0.0` onwards

**module**: `any`

### Description

**Describe the bug**

As mentioned in #309, the following error occurs when using the latest `v3.0.0` or newer version of the Azure provider for Terraform:
```shell
│ Error: Unsupported argument
│ 
│   on .terraform/modules/enterprise_scale/resources.connectivity.tf line 122, in resource "azurerm_public_ip" "connectivity":
│  122:   availability_zone       = each.value.template.availability_zone
│ 
│ An argument named "availability_zone" is not expected here.
```

**Steps to Reproduce**

1. Configure a root module using `v1.1.4` of the module, and set a version constraint on the provider required version to `v3.0.0` or later.
2. Run `terraform init -upgrade`
3. Run `terraform plan`
4. Observe the error.

**Screenshots**

- Image taken from #309</br>
  image

**Additional context**

This resource attribute was "hard" deprecated in `v3.0.0` so no opportunity was available to make the transition whilst offering support for `v2.x` of the provider.

As such, this will require a complete shift of the module only support provider versions from `v3.0.0` onwards. `v2.x` of the provider will no longer work so need to consider whether this requires a `major` release to support, or will `minor` suffice?

### LINKED ISSUE #333: VPN Gateway Generations
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

An error message appears when attempting to deploy the VPN gateway in the hub with the SKU VpnGw5AZ. This deployment automatically determined the gateway generation as generation 1 and the SKU is not available. The following advanced configuration needs to be used in order to successfully deploy the VPN gateway as this SKU.

```hcl
  advanced = {
    custom_settings_by_resource_type = {
      azurerm_virtual_network_gateway = {
        connectivity = {
          vpngw = {
            (var.connectivity_resources_location) = {
              generation = "Generation2"
            }
          }
        }
      }
    }
  }
```

It would be good if this could be rectified automatically, or if we can specify the gateway generation manually without using the advanced configuration.

### LINKED ISSUE #334: BGP configuration on VPN gateways
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Can we request for BGP parameters to be exposed on the VPN gateways please. These currently have to be configured through the advanced configuration as per the example below.

```hcl
  advanced = {
    custom_settings_by_resource_type = {
      azurerm_virtual_network_gateway = {
        connectivity = {
          vpngw = {
            (var.connectivity_resources_location) = {
              enable_bgp    = true
              bgp_settings = [{
                asn               = "65515"
                peering_addresses = ["xx.xx.xx.xx"]
              }]
            }
          }
        }
      }
    }
  }
```

### LINKED ISSUE #340: Call to function "coalesce" failed: all arguments must have the same type.
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: v1.1.8

**azure provider**: v2.99.0

**module**: v1.1.4 (based on main branch of repository, latest commit: 0b343c6ba9ce4595a0e494f97d2a439845a1cb2a)

### Description

When specifying the advanced block of the `configure_connectivity_resources`  input as follows:
```
advanced = {
      resource_prefix                           = "pre"
      resource_suffix                           = "suf"
      existing_ddos_protection_plan_resource_id = ""
      existing_virtual_wan_resource_id          = ""
      resource_group_per_virtual_hub_location   = false
      custom_settings_by_resource_type = {
        azurerm_resource_group = {
          virtual_wan = {
            (local.default_location) = {
              name = local.connectivity_resource_group_name
            }
          }
      }
    }
  }
```
I encounter an error as shown here. I suspect at some point an unintended type conversion was performed by terraform. 

```
│   Error: Error in function call
│
│   on .terraform\modules\enterprise_scale\locals.tf line 53, in locals:
│   53:   connectivity_resources_advanced = coalesce(local.configure_connectivity_resources.advanced, local.empty_map)
│     ├────────────────
│     │ local.configure_connectivity_resources.advanced is object with 6 attributes
│     │ local.empty_map is object with no attributes
│
│ Call to function "coalesce" failed: all arguments must have the same type.
```

**Steps to Reproduce**

1. Specify the advanced block as shown previously
2. `terraform plan`

**Additional Context**

I managed to solve this issue locally when explicitly casting the `local.empty_map` as type `map `using `tomap()` (`locals.tf`, line 5).

```
# The following block of locals are used to avoid using
# empty object types in the code
locals {
  empty_list   = []
  empty_map    = tomap({})
  empty_string = ""
}
```

### LINKED ISSUE #342: Ability to rename ASC export resource group name
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
Discussed with Kevin to have the ability to rename ASC export resource groups names for a customer deployment, submitting this feature request per discussion

**Additional context**

### PR DESCRIPTION
**Pull request by krowlandson**
## Overview/Summary

This PR contains a number of small updates to address issues from our backlog as listed below

## This PR fixes/adds/changes/removes

1. Update module to support the AzureRM provider for Terraform from version `v3.0.2` onwards:
    1. Fix #309
    2. Fix #319
2. The `threat_intel_mode` value for `azurerm_firewall` resources is now explicitly set with a default value of `Alert` to support the latest provider versions. This matches the previous "default" value of the old provider.
3. Cast `empty_map` local to the `tomap()` function to fix #340 
4. Added new variable `asc_export_resource_group_name` to fix #342
6. Add logic to automatically configure the `generation` value for VPN gateways without using the `advanced` object to fix #333
7. Added input variables and logic to simplify configuring active-active mode for VPN gateways without using the `advanced` object to fix #232 
8. Added logic to suppress creation of Public IP resource(s) when a custom `ip_configuration` input is specified via the `advanced` block for the following resource types:
    1. `azurerm_virtual_network_gateway` (ExpressRoute and VPN)
    2. `azurerm_firewall`
9. Added input variables for BGP configuration settings without using the `advanced` object to fix #334
10. Added missing `vpn_auth_types` attribute for the `vpn_client_configuration` block on Virtual Network Gateway resources
11. Updated Wiki docs to reflect the included changes where covered in documentation
12. Updated test framework to provide coverage of the included fixes
13. Updated test strategy to ensure working versions are included from `v0.15.1` (new minimum required to fix `Error: Output refers to sensitive values`) to latest `v1.1.x`

### Breaking Changes

1. To support the AzureRM provider for Terraform from version `v3.0.2` onwards; To configure availability zones for `azurerm_public_ip` resources using the `advanced` input, you must now provide zone inputs as a collection of string values within a `zones` input, as `availability_zone` is no longer supported by the provider. Valid values (at the time of writing), include:
    1. "No-Zone",
    2. "1",
    4. "2",
    5. "3",
    6. "Zone-Redundant",
2. By setting a preference to `Generation2` for supported VPN gateway SKUs, customers may have their VPN gateway redeployed to the new version. Instructions for how to override this must be added to the release notes.
4. In order to address some of the issues fixed above, we have had to make breaking changes to the mandatory schema. This will result in an error at `plan` until users update the input for `configure_connectivity_resources`. Longer term objective is to reduce the number of mandatory attributes within the schema using the `optional()` type wrapper once released as GA.

## Testing Evidence

Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.
- [ ] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located in the [Enterprise-Scale repo](https://github.com/Azure/Enterprise-Scale) in the directory: `/docs/wiki/whats-new.md`)

### CODE REVIEW

**Comment by krowlandson** [comment]
Should simplify and may also fix the issue described in #259 but requires further investigation.

**Comment by krowlandson** [comment]
image

New test strategy picking up correct versions 👍🏻

**Review by matt-FFFFFF — APPROVED** [review]
:shipit:

**Pull request merged**
