### PR TITLE
Updated references from docs.microsoft.com to learn.microsoft - Part 1

### PR DESCRIPTION
**Pull request by ElYusubov**
## Overview/Summary

Updated references from docs.microsoft.com to learn.microsoft.
The PR has two commits that update the reference URLs in the documentation.

## This PR fixes/adds/changes/removes

1. Replaces the references in the document links to the latest learn.microsoft links. 

### Breaking Changes

1. No breaking changes, document updates only.

## Testing Evidence

Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

## As part of this Pull Request I have

- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pulls)
- [ ] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues), for tracking and closure.
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main)
- [ ] Performed testing and provided evidence.
- [ ] Updated relevant and associated documentation.
- [ ] Updated the ["RELEASE"](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues) page with details needed for when this code change is released.

### CODE REVIEW

**Comment by krowlandson** [comment]
Thank you for this important piece of housekeeping @ElYusubov 🚀 

I notice you have updated this since it was first opened. Please let me know when you are happy that all instances are covered and I will add this to my list for review 👍🏻

**Comment by ElYusubov** [comment]
Hi @krowlandson - Thank you for a follow up!
I am done with editing the documentation and reference links.

**Comment by krowlandson** [comment]
> Hi @krowlandson - Thank you for a follow up! I am done with editing the documentation and reference links.

Great, thank you @ElYusubov. I will review this next week 👍🏻

**Review by krowlandson — APPROVED** [review]
Thank you for the PR @ElYusubov. I found a few missing links which needed updating, but have updated these and pushed to your PR so it's ready to merge now.

LGTM 👍🏻

**Review by krowlandson — APPROVED** [review]
LGTM

**Pull request merged**
