### PR TITLE
Module Telemetry Enhancements/Additions - Custom Library & Zero Trust Networking Phase 1

### PR DESCRIPTION
**Pull request by jtracey93**
## Overview/Summary

This PR adds adds some new telemetry collection to the existing bitfield deployments so we can learn more about how the module is being used.

## This PR fixes/adds/changes/removes

1. [AB#27173](https://dev.azure.com/CSUSolEng/2a9d5a5a-8998-4ad0-81c8-ef3045e4da97/_workitems/edit/27173) - Zero Trust Networking Phase 1 - https://github.com/Azure/Enterprise-Scale/wiki/Deploying-ALZ-CustomerUsage#alz-acceleratoreslz-arm-deployment---zero-trust-networking---phase-1--definition
2. Telemetry for Custom Library Enabled

### Breaking Changes

None

## Testing Evidence
image
Screenshot of deploying module with defaults and then adding connectivity config with AzFW Premium 

Can be seen on internal dashboards from test deployment

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.

### CODE REVIEW

**Comment by jtracey93** [comment]
@matt-FFFFFF all good now

**Review by matt-FFFFFF — APPROVED** [review]

**Pull request merged**
