### PR TITLE
feat(connectivity): custom Settings for Virtual Hub connection names

### PR DESCRIPTION
**Pull request by birdnathan**
## Overview/Summary

Been an outstanding request for a while but finally got a chance to look at this properly. The additional capability will allow users to override a Virtual Hub Virtual Network Connection name. The logic is the same as what was added for hub/spoke peerings via https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pull/401

## This PR fixes/adds/changes/removes

1.  https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/633

## Testing Evidence

Evidence from local run:

Virtual Network Resource IDs added to relevant arrays withing settings.connectivity.tf:
image
Without a custom setting we get a randomly generated connection name:
image
With the custom setting for the target virtual network resource id added to the settings.connectivity.tf:
image
The random name is overridden:
image
Portal Views following deployment:
image
image

Adding a custom setting to a currently connected virtual network or changing the name will destroy and recreate the connection. Terraform waits for the destroy to complete before re-adding the connection.
image

## As part of this Pull Request I have

- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pulls)
- [X] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues), for tracking and closure.
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main)
- [X] Performed testing and provided evidence.
- [X] Updated relevant and associated documentation.

### CODE REVIEW

**Comment by birdnathan** [comment]
@microsoft-github-policy-service agree

________________________________

**Comment by birdnathan** [comment]
@matt-FFFFFF - Can we get this reviewed at all? About to deploy a large vwan architecture for a customer and be nice to have this available to use. TIA

**Comment by matt-FFFFFF** [comment]
Hi @birdnathan 

Sorry this slipped through the net

Thank you so much for the work here. I will review properly next week

**Comment by matt-FFFFFF** [comment]
@birdnathan looks like the linter isn't happy 🙂

`Warning: local.virtual_hub_connection_resource_id is declared but not used (terraform_unused_declarations)`

Did you mean to use this local anywhere?

**Comment by birdnathan** [comment]
@matt-FFFFFF - Fix committed.

**Comment by matt-FFFFFF** [comment]
Hi @birdnathan 

The tests are giving this error on plan - the test in question is in the `tests/modules/test_001_baseline` dir if you want to try it yourself.

```text
╷
│ Error: Invalid index
│ 
│   on ../../../modules/connectivity/locals.tf line 1847, in locals:
│ 1847:           resource_id       = local.virtual_hub_connection_resource_id[location][spoke_resource_id]
│     ├────────────────
│     │ local.virtual_hub_connection_resource_id is object with 3 attributes
│ 
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│ 
│   on ../../../modules/connectivity/locals.tf line 1850, in locals:
│ 1850:           name                      = local.virtual_hub_connection_name[location][spoke_resource_id]
│     ├────────────────
│     │ local.virtual_hub_connection_name is object with 3 attributes
│ 
│ The given key does not identify an element in this collection value.
╵
make: *** [Makefile:41: tf-plan] Error 1

```

**Comment by birdnathan** [comment]
How's that now @matt-FFFFFF ? The more I looked at it the simpler I could actually make it 🙃

**Review by matt-FFFFFF — APPROVED** [review]

**Comment by matt-FFFFFF** [comment]
Looks good @birdnathan 

Thanks for your efforts here. Just running final test and will merge

**Pull request merged**
