### PR TITLE
Allow the creation of GatewaySubnets and AzureFirewallSubnets without NSGs

### PR DESCRIPTION
**Pull request by nspyke**
Azure does not permit the creation of a GatewaySubnet or AzureFirewallSubnet with a NSG.

### CODE REVIEW

**Comment by krowlandson** [comment]
Thank you for the contribution @nspyke... Looks good but I'm going to be doing a full Policy refresh soon as we've had some major updates in the ES reference deployment which need pulling across. I'll use this to ensure we pull this fix across too though, in case this was missed.

**Comment by nspyke** [comment]
I've come across a related issue. 
At present, the Terraform AzureRM provider only supports the creation of subnet resources with network security groups as an inline subnet definition on the virtual network resource. 
It does not allow the setting of a NSG on a separate subnet resource, which instead it must be associated to a subnet after subnet creation, which is in direct conflict to this policy.
And if you use the inline subnet definition, the provider does not support the setting of delegation or service endpoints on that inline definition.

So for now, I've had to add an exemption until Terraform AzureRM is able to support the features required to re-enable it.

**Comment by krowlandson** [comment]
Hi @nspyke...

Just circling back on this PR as I'm looking to update the policies on our next release and this has also been mentioned in #38.

This policy is also a bit problematic within Terraform as you mention.

I've escalated this internally, as the provider used to implement the NSG and UDR associations within the "property bag" of the subnet resource, however there's a wholesale move across all SDKs to create the association through a dedicated resource (e.g. [`azurerm_subnet_network_security_group_association`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subnet_network_security_group_association) and [`azurerm_subnet_route_table_association`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subnet_route_table_association)). Terraform also benefits from this "new" approach as it addresses a number of other issues relating to state tracking, but this also results in the problem you've identified. This happens because Terraform breaks down the declarative template into a series of imperative API calls against ARM. This means Azure Policy [correctly] blocks Subnet creations when they're missing the NSG association, even though you have an NSG association in your Terraform deployment, because Azure Policy doesn't know that you have a subsequent "call in the queue" to attach the NSG.

If you can log this issue as a support ticket through the Azure Portal and mention me in it, I'll see if I can find the ticket to attach my previous correspondence to it regarding this topic. Hopefully this will help with the escalation.

**Comment by jtracey93** [comment]
adding link to https://github.com/Azure/Enterprise-Scale/issues/456

**Comment by jtracey93** [comment]
Hi @nspyke, going to close this PR, as going to fix upstream in the ESLZ repo policies as part of this PR https://github.com/Azure/Enterprise-Scale/pull/630

Once that PR is merged it will be updated into the Terraform module.

Thanks 

Jack

**Pull request closed without merging**
