### PR TITLE
docs: update examples

### PR DESCRIPTION
**Pull request by matt-FFFFFF**
## Overview/Summary

Doc updates for v4

### CODE REVIEW

**Comment by jaredfholgate** [comment]
@matt-FFFFFF I came for a review, but I hijacked it to add some more doc and example fixes. Hope that is ok. Feel free to revert my commit if this is not the right PR for them.

**Review by jaredfholgate — APPROVED** [review]
LGTM

**Comment by matt-FFFFFF** [comment]
Thanks @jaredfholgate for the additional fixes!

**Pull request merged**
