### PR TITLE
fix: policy_assignment_es_deploy_log_analytics enforcementMode

### PR DESCRIPTION
**Pull request by matt-FFFFFF**
## Overview/Summary

Fixes [AB#29081](https://dev.azure.com/CSUSolEng/2a9d5a5a-8998-4ad0-81c8-ef3045e4da97/_workitems/edit/29081)

## This PR fixes/adds/changes/removes

1. Changes enforcementmode of deploy LAW policy 

## Testing Evidence

by inspection

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main)
- [ ] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.

### CODE REVIEW

**Comment by matt-FFFFFF** [comment]
AB#20981

**Review by jtracey93 — APPROVED** [review]

**Pull request merged**
