### PR TITLE
Add option to add identity block to an Automation Account

### LINKED ISSUE #398: Feature Request: Add option to add Identity block to an Automation Account.
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**Is your feature request related to a problem?**

We would like to be able to add an Identity on at least the Automation Account resource in the management. At this point we can only change the name, but it is not possible to set the identity an Automation Account is run. I think the best location would be in the advanced part of the configure_management_resources variable.

**Describe the solution you'd like**

```
configure_management_resources = {
    "advanced" = {
      custom_settings_by_resource_type = {
        azurerm_resource_group = {
          management = {
            name = "management"
          }
        }
        azurerm_automation_account = {
          management = {
            name = "management"
            identity = {
               type = "SystemAssigned, UserAssigned"
               identity_ids = "identity ID"
           }
          }
        }
        azurerm_log_analytics_workspace = {
          management = {
            name = "management"
          }
        }
      }
    }
    "location" : "west...........

```
**Additional context**

### PR DESCRIPTION
**Pull request by matt-FFFFFF**
## Overview/Summary

Replace this with a brief description of what this Pull Request fixes, changes, etc.

## This PR fixes/adds/changes/removes

1. Fixes #398 

## Testing Evidence

```text
 ARM_SUBSCRIPTION_ID="00000000-0000-0000-0000-000000000000" make TESTPREFIX='TestManagementAdvanced' terratest
==> Running Go test...
cd tests/terratest && go test $(go list ./... |grep -v 'vendor'|grep -v 'utils')  -run ^TestManagementAdvanced
ok  	github.com/Azure/terraform-azurerm-caf-enterprise-scale/tests/terratest/connectivity/advancedVnetPeeringName	0.190s [no tests to run]
ok  	github.com/Azure/terraform-azurerm-caf-enterprise-scale/tests/terratest/management/advancedAutomationAccountIdentity	10.888s
```

Note: `identity` block must be enclosed in a list `[ ... ]`

```terraform
module "alz" {
  source  = "Azure/caf-enterprise-scale/azurerm"
  version = "2.x.x"
  # ... removed mandatory vars
  advanced = {
    custom_settings_by_resource_type = {
      azurerm_automation_account = {
        management = {
          identity = [
            {
              type = "SystemAssigned, UserAssigned"
              identity_ids = [
                "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/test/providers/Microsoft.ManagedIdentity/userAssignedIdentities/test-id"
              ]
            }
          ]
        }
      }
    }
  }
}

```

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.
- [ ] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located in the [Enterprise-Scale repo](https://github.com/Azure/Enterprise-Scale) in the directory: `/docs/wiki/whats-new.md`)

### CODE REVIEW

**Review by krowlandson — APPROVED** [review]
LGTM 🚀

**Comment by mlomat** [comment]
Thanks @matt-FFFFFF for this feature, perfect timing for myself :). Maybe will be also good option to add System Managed Identity for Automation Account as default option for new automation accounts creation?

**Comment by matt-FFFFFF** [comment]
Hi @mlomat,

Thanks for the suggestion!

Doing this would modify existing deployments so will hold off for now and discuss with @krowlandson.

Matt

**Comment by mlomat** [comment]
Sure, I understand that. From my perspective, I just tested it because I added SystemIdentity manually on Azure portal.
Framework wanted to remove it after reapply, because terraform find out that state of AA has changed. So I found out your change to version 2.1.2 and I added custom config: 

```
 advanced = {
      custom_settings_by_resource_type = {
        azurerm_automation_account = {
          management = {
            identity = [
              {
              type = "SystemAssigned"
              }
            ]
          }
        }
      }
    }
```

After that, it doesn't want to remove it anymore. So I think no harm to add it as default. 

Have a great weekend!
Best
Mateusz

**Comment by matt-FFFFFF** [comment]
@mlomat thanks!

**Pull request merged**
