### PR TITLE
Add `Edit-LineEndings` to simplify local running

### PR DESCRIPTION
**Pull request by krowlandson**
## Overview/Summary

Previously, files would be created with `CRLF` line endings when running the `Invoke-LibraryUpdate` script on Windows.

This PR adds a new `Edit-LineEndings` function to simplify local running of the `Invoke-LibraryUpdate.ps1` script on different OS versions to ensure the original `LF` line endings are used.

This prevents Git from incorrectly tracking changes to files which have had the line endings incorrectly updated.

> The default is line ending type is set to `unix` (aka `LF`) on the assumption that git is configured to "check out as is". Users may need to change this value if git is configured differently.

## This PR fixes/adds/changes/removes

1. Adds a new `Edit-LineEndings` function
2. Updates the `Export-LibraryArtifact` function to use `Edit-LineEndings`
3. Updates the `Invoke-LibraryUpdate` script to use `Edit-LineEndings`

### Breaking Changes

n/a

## Testing Evidence

**Run on local machine (Windows)**

image

**Run on GitHub runner (Linux)**

image

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.
- [x] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located in the [Enterprise-Scale repo](https://github.com/Azure/Enterprise-Scale) in the directory: `/docs/wiki/whats-new.md`)

### CODE REVIEW

**Comment by matt-FFFFFF** [comment]
Isn't this better enforced with Git and .gitattributes?

https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#per-repository-settings

**Comment by krowlandson** [comment]
> Isn't this better enforced with Git and .gitattributes?
> 
> https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#per-repository-settings

This is probably a good addition, however I think this is in addition to rather than instead of the proposed change?

**Review by matt-FFFFFF — APPROVED** [review]
lgtm

**Review by matt-FFFFFF — APPROVED** [review]

**Pull request merged**
