### PR TITLE
Add practical code examples

### LINKED ISSUE #186: Policies incompatible with Terraform
<h3 id=communitynote>Community Note </h3>
<ul>
<li>Please vote on this issue by adding a &#128077; <a href="https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/">reaction</a> to the original issue to help the community and maintainers prioritize this request </li>
<li>Please do not leave &quot;+1&quot; or &quot;me too&quot; comments, they generate extra noise for issue followers and do not help prioritize the request </li>
<li>If you are interested in working on this issue or have submitted a pull request, please leave a comment </li>
</ul>
<h3 id=versions>Versions </h3>
<p><strong>terraform</strong>: <em>all</em> </p>
<p><strong>azure provider</strong>: <em>all</em> </p>
<p><strong>module</strong>: <em>all</em> </p>
<h3 id=description>Description </h3>
<p>Due to the way the <code>azurerm</code> provider works, the following Policy Definitions are incompatible with Terraform: </p>
<ul>
<li><code>Deny-Subnet-Without-NSG</code> </li>
<li><code>Deny-Subnet-Without-UDR</code> </li>
</ul>
<p><strong>Steps to Reproduce</strong> </p>
<ol>
<li>Create a deployment where these policies are assigned at a specific scope. </li>
<li>Place a Subscription under this scope. </li>
<li>Try to create a Virtual Network with Subnets missing NSG and UDR configurations (note that even if you add these using the approach available by Terraform, the deployment fails) </li>
</ol>
<p><strong>Screenshots</strong> </p>
<p><strong>Additional context</strong> </p>

### LINKED ISSUE #359: Specifying parameters in policy assignment loses Log Analytics ID
<h3 id=communitynote>Community Note </h3>
<ul>
<li>Please vote on this issue by adding a &#128077; <a href="https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/">reaction</a> to the original issue to help the community and maintainers prioritize this request </li>
<li>Please do not leave &quot;+1&quot; or &quot;me too&quot; comments, they generate extra noise for issue followers and do not help prioritize the request </li>
<li>If you are interested in working on this issue or have submitted a pull request, please leave a comment </li>
</ul>
<h3 id=versions>Versions </h3>
<p><strong>terraform</strong>: 1.1.7 </p>
<p><strong>azure provider</strong>: 3.0.2 </p>
<p><strong>module</strong>: 2.0.0 </p>
<h3 id=description>Description </h3>
<p><strong>Describe the bug</strong> </p>
<p>I'm trying to set a parameter on a policy to disable logging of Azure Firewalls to the Log Analytics resource as per a company requirement. I'm not sure whether I am adding the parameter to the correct place in the policy but I am configuring the following set of locals in my code: </p>
<pre><code>locals {
  archetype_config_overrides = {
    root = {
      archetype_id   = &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;es_root&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;
      parameters     = {
        Deploy-Resource-Diag = {
          FirewallLogAnalyticsEffect = &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;Disabled&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;
        }
      }
      access_control = local.empty_map
    }
  }
}
</code></pre>
<p>This creates the following change in Terraform: </p>
<pre><code>module.enterprise_scale.azurerm_management_group_policy_assignment.enterprise_scale[&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;/providers/Microsoft.Management/managementGroups/[correct-mg]/providers/Microsoft.Authorization/policyAssignments/Deploy-Resource-Diag&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;] will be updated in-place
  ~ resource &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;azurerm_management_group_policy_assignment&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot; &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;enterprise_scale&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot; {
        id                   = &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;/providers/Microsoft.Management/managementGroups/[correct-mg]/providers/Microsoft.Authorization/policyAssignments/Deploy-Resource-Diag&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;
        name                 = &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;Deploy-Resource-Diag&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;
      ~ parameters           = jsonencode(
          ~ {
              + FirewallLogAnalyticsEffect = {
                  + value = &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;Disabled&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;
                }
              ~ logAnalytics               = {
                  ~ value = &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;/subscriptions/[correct-id]/resourceGroups/[correct-rg]/providers/Microsoft.OperationalInsights/workspaces/[correct-workspace]&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot; -&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;gt; &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/[correct-rg]/providers/Microsoft.OperationalInsights/workspaces/[correct-workspace]&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;
                }
            }
        )
        # (8 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
</code></pre>
<p>Is this even the correct way of disabling the functionality of that policy (by sending in the parameter into the policy assignment) and if so what is causing the additional parameter to cause the subscription ID to be lost? </p>

### PR DESCRIPTION
**Pull request by DevSecNinja**
## Overview/Summary

Adding practical examples to the Docs

- Fix #359
- Fix #186

## As part of this Pull Request I have

- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pulls)
- [ ] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues), for tracking and closure.
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main)
- [ ] Performed testing and provided evidence.
- [ ] Updated relevant and associated documentation.
- [ ] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located in the [Enterprise-Scale repo](https://github.com/Azure/Enterprise-Scale) in the directory: `/docs/wiki/whats-new.md`)

Related: #186

### CODE REVIEW

**Comment by krowlandson** [comment]
Thank you for your contribution @DevSecNinja 👍🏻 

As discussed offline, if we can expand this to cover off some of our related issues, that would be awesome.

I think the following would be good ones to consider closing off with this:

- #359 
- #186 

To deliver this I think it would be good to create a dedicated level 200 example page showing how to set custom parameters on policy assignments, covering the following available ways:

- Within an archetype definition
- Setting static parameter values within a policy assignment template (within the custom `lib` folder)
- Within the `archetype_config_overrides` input variable
- Within the `custom_landing_zones` input variable

If we can build examples showing how to disable the policies mentioned in #186, we can then link to these from the [Getting Started](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Getting-Started#additional-considerations-when-deploying-landing-zone-resources-with-terraform) page (which also needs updating to identify `Deny-Subnet-Without-Udr` as another policy which may conflict with Terraform.

Finally, we can also update the [Archetype Definitions](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Archetype-Definitions) page to point to these examples when talking about the `parameters` object within the `archetype_config` object.

If you have any further questions on this, please let me know 🚀

**Comment by DevSecNinja** [comment]
Closes #35 #186

**Comment by DevSecNinja** [comment]
> Thank you for your contribution @DevSecNinja 👍🏻
> 
> As discussed offline, if we can expand this to cover off some of our related issues, that would be awesome.
> 
> I think the following would be good ones to consider closing off with this:
> 
> * [Specifying parameters in policy assignment loses Log Analytics ID #359](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/359)
> * [Policies incompatible with Terraform #186](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/186)
> 
> To deliver this I think it would be good to create a dedicated level 200 example page showing how to set custom parameters on policy assignments, covering the following available ways:
> 
> * Within an archetype definition
> * Setting static parameter values within a policy assignment template (within the custom `lib` folder)
> * Within the `archetype_config_overrides` input variable
> * Within the `custom_landing_zones` input variable
> 
> If we can build examples showing how to disable the policies mentioned in #186, we can then link to these from the [Getting Started](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Getting-Started#additional-considerations-when-deploying-landing-zone-resources-with-terraform) page (which also needs updating to identify `Deny-Subnet-Without-Udr` as another policy which may conflict with Terraform.
> 
> Finally, we can also update the [Archetype Definitions](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BUser-Guide%5D-Archetype-Definitions) page to point to these examples when talking about the `parameters` object within the `archetype_config` object.
> 
> If you have any further questions on this, please let me know 🚀

All points done in latest commit, except for your point on `Deny-Subnet-Without-Udr`. What's the matter with that one? Similar issue as `Deny-Subnet-Without-Nsg` as the subnet creation + NSG linking can't be done in one API call, causing the deployment to fail with a policy validation error?

**Comment by krowlandson** [comment]
Thank you for the updates @DevSecNinja ...

> All points done in latest commit, except for your point on `Deny-Subnet-Without-Udr`. What's the matter with that one? Similar issue as `Deny-Subnet-Without-Nsg` as the subnet creation + NSG linking can't be done in one API call, causing the deployment to fail with a policy validation error?

Yes, as Terraform links UDRs to subnets using the [azurerm_subnet_route_table_association](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subnet_route_table_association) resource, it's not possible to create a subnet with the UDR attached.

I've fixed a couple of linting errors and will review the PR now 👍🏻

**Review by krowlandson — APPROVED** [review]
LGTM 🚀

**Pull request merged**
