### PR TITLE
fix(management): azapi_resource.diag_settings

### PR DESCRIPTION
**Pull request by Laudenlaruto**
## Overview/Summary

Fixes a regression in 6.0.0

## This PR fixes/adds/changes/removes

1. #1024 

## Testing Evidence

Tested in locally and it works.

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.

### CODE REVIEW

**Comment by Laudenlaruto** [comment]
It works but when updating it, it want to recreate the resource.
```
  # azapi_resource.diag_settings["/providers/Microsoft.Management/managementGroups/xxx-sandboxes"] must be replaced
-/+ resource "azapi_resource" "diag_settings" {
      ~ id                        = "/providers/Microsoft.Management/managementGroups/xxx-sandboxes/providers/Microsoft.Insights/diagnosticSettings/toLA" -> (known after apply)
      - location                  = "global" -> null # forces replacement
        name                      = "toLA"
      ~ output                    = jsonencode({}) -> (known after apply)
        # (7 unchanged attributes hidden)
    }
```

**Comment by Laudenlaruto** [comment]
It works when I added `schema_validation_enabled = false`

**Comment by qaiserali** [comment]
> schema_validation_enabled

I don't think it is good idea to set schema_validation_enabled to false.

**Comment by Laudenlaruto** [comment]
Needed to change 
`  location                  = "global"`
otherwise It wants to replace it everytime I apply
`      ~ location                  = "global" -> "francecentral" # forces replacement`

**Comment by matt-FFFFFF** [comment]
Thank you for your PR! Will run through the tests

**Review by matt-FFFFFF — APPROVED** [review]

**Comment by qaiser-tele2** [comment]
@matt-FFFFFF  When are you planning to merge this with v6.0.0?

**Comment by qaiserali** [comment]
@matt-FFFFFF  When are you planning to merge this with v6.0.0?

**Comment by qaiserali** [comment]
I can confirm that this is still an issue with v6.1.0

It still wants to replace when run the tf apply command

`~ location                  = "global" -> "null" # forces replacement`

**Pull request merged**
