### PR TITLE
Add new attributes for management resources

### LINKED ISSUE #492: Feature Request - configure automation account in management subscription
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Is your feature request related to a problem?

There is no possibility to configure automation account network integration that is deployed as part of management environment.  

#### Describe the solution you'd like

Would be great to have parameter in settings.management.tf like:

aa_public_network_access_enable=true/false

### PR DESCRIPTION
**Pull request by krowlandson**
## Overview/Summary

This PR adds new attributes for the following resources:

- azurerm_log_analytics_workspace
- azurerm_automation_account

These new attributes are initially only customizable using the `advanced` input as we don't currently anticipate this to be a common ask.

## This PR fixes/adds/changes/removes

1. Fixes #492

### Breaking Changes

none

## Testing Evidence

Adding the following to the test framework settings:

```hcl
  configure_management_resources = {
    # Existing attributes removed for brevity
    advanced = {
      # Existing attributes removed for brevity
      custom_settings_by_resource_type = {
        azurerm_automation_account = {
          management = {
            public_network_access_enabled = false
            local_authentication_enabled  = false
          }
        }
        azurerm_log_analytics_workspace = {
          management = {
            cmk_for_query_forced = true
          }
        }
      }
    }
  }
```

image showing diff on settings

Results in the following changes to the `baseline_values.json` for `test_003_add_mgmt_conn`:

image showing changes for azurerm_automation_account

image showing changes for azurerm_log_analytics_workspace

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.
- [x] Updated the ["RELEASE"](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues) page with details needed for when this code change is released.

### CODE REVIEW

**Comment by krowlandson** [comment]
No changes in `baseline_values.json` as expected.

@prjelesi, regarding #492 what are your thoughts on only making these settings available through the `advanced` inputs? I'm reluctant to add them to the input variables unless we see demand from multiple customers.

I have also added some other missing attributes for the `azurerm_log_analytics_workspace` and `azurerm_automation_account` resources.

**Review by matt-FFFFFF — APPROVED** [review]

**Pull request merged**
