### PR TITLE
Update `Docs/Wiki Sync` to check for changes

### PR DESCRIPTION
**Pull request by krowlandson**
<h2 id=overviewsummary>Overview/Summary </h2>
<p>This PR update the GitHub Action <code>Docs/Wiki Sync</code> to check for changes before trying to commit and push to the Wiki repository. </p>
<h2 id=thisprfixesaddschangesremoves>This PR fixes/adds/changes/removes </h2>
<ol>
<li>This PR prevents the following error from occurring: </li>
</ol>
<p>Image showing wiki sync error </p>
<h3 id=breakingchanges>Breaking Changes </h3>
<p>none </p>
<h2 id=testingevidence>Testing Evidence </h2>
<p>Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate). </p>
<p>Two concurrent runs: </p>
<p> </p>
<p>First run successfully updates the Wiki with changes: </p>
<p> </p>
<p>Second run detects no changes and gracefully completes: </p>
<p> </p>
<h2 id=aspartofthispullrequestihave>As part of this Pull Request I have </h2>
<ul>
<li>[x] Checked for duplicate <a href="https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pulls">Pull Requests</a> </li>
<li>[x] Associated it with relevant <a href="https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues">issues</a>, for tracking and closure. </li>
<li>[x] Ensured my code/branch is up-to-date with the latest changes in the <code>main</code> <a href="https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main">branch</a> </li>
<li>[x] Performed testing and provided evidence. </li>
<li>[x] Updated relevant and associated documentation. </li>
<li>[x] Updated the <a href="https://github.com/Azure/Enterprise-Scale/wiki/Whats-new">&quot;What's New?&quot;</a> wiki page (located in the <a href="https://github.com/Azure/Enterprise-Scale">Enterprise-Scale repo</a> in the directory: <code>/docs/wiki/whats-new.md</code>) </li>
</ul>

### CODE REVIEW

**Comment by krowlandson** [comment]
@matt-FFFFFF - I will be including this update in a PR on the ES repo soon too JFYI

**Comment by krowlandson** [comment]
cc: @jtracey93

**Review by jtracey93 — APPROVED** [review]
LGTM 🚢

**Pull request merged**
