### PR TITLE
Remove Arc monitoring policy assignments from root

### PR DESCRIPTION
**Pull request by Springstone**
## Overview/Summary

Removed the Linux and Windows Arc monitoring policy assignment from intermediate root.

Linked PR for doc update [here](https://github.com/Azure/Enterprise-Scale/pull/1108)

## This PR fixes/adds/changes/removes

1. Updated archetype root definition: archetype_definition_es_root.tmpl.json
2. Cleanup: deleted policy_assignment_es_deploy_ws_arc_monitoring.tmpl.json
3. Cleanup: deleted policy_assignment_es_deploy_lx_arc_monitoring.tmpl.json

## Breaking Changes

1. Removed as these policies are deployed as part of the "Enable Azure Monitor for VMs" Policy Set/Initiative

## Testing Evidence

Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

## As part of this Pull Request I have

- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pulls)
- [ ] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues), for tracking and closure.
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main)
- [ ] Performed testing and provided evidence.
- [X] Updated relevant and associated documentation.
- [ ] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located in the [Enterprise-Scale repo](https://github.com/Azure/Enterprise-Scale) in the directory: `/docs/wiki/whats-new.md`)

### CODE REVIEW

**Comment by matt-FFFFFF** [comment]
This could be a breaking change for customers. Do we need an article in the wiki describing how to re-assign these policies if required (using archetype extensions)?

**Comment by krowlandson** [comment]
I'm clearly out of the loop here, but why were these assignments removed? Have they been replaced by something else?

**Comment by Springstone** [comment]
> I'm clearly out of the loop here, but why were these assignments removed? Have they been replaced by something else?

They're not deployed as part of the other RIs and doesn't make sense to deploy this at root.

**Review by krowlandson — APPROVED** [review]
LGTM

**Pull request merged**
