### PR TITLE
Add more values to built-in `template_file_variables`

### LINKED ISSUE #255: Bug Report - How do we reference the existing management log analytics workspace in custom assignments please?
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 0.15.0

**azure provider**: Unknown

**module**: 1.0.0

### Description

There appears to be no apparent way to reference the log analytics instance id as part of a policy assignment. Can we get clarity on this please?

Policy assignment stands as follows, copying from the definition for the inbuilt assignment policy_assignment_es_deploy_azactivity_log.tmpl.json...

{
  "name": "Deploy-LAA-Subs",
  "type": "Microsoft.Authorization/policyAssignments",
  "apiVersion": "2019-09-01",
  "properties": {
    "description": "Allow Security Center to auto provision the Log Analytics agent on your subscriptions to monitor and collect security data using a custom workspace.",
    "displayName": "Enable Security Center's auto provisioning of the Log Analytics agent on your subscriptions with custom workspace.",
    "notScopes": [],
    "parameters": {
      "logAnalytics": {
        "metadata": {
          "description": "Select Log Analytics workspace from dropdown list. If this workspace is outside of the scope of the assignment you must manually grant 'Log Analytics Contributor' permissions (or similar) to the policy assignment's principal ID.",
          "displayName": "Log Analytics workspace",
          "strongType": "omsWorkspace"
        },
        "type": "String",
        "value": "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/${root_scope_id}-mgmt/providers/Microsoft.OperationalInsights/workspaces/${root_scope_id}-la"
      }
    },
    "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/8e7da0a5-0a0e-4bbc-bfc0-7773c018b616",
    "scope": "${current_scope_resource_id}",
    "enforcementMode": "Default"
  },
  "location": "${default_location}",
  "identity": {
    "type": "SystemAssigned"
  }

### PR DESCRIPTION
**Pull request by krowlandson**
## Overview/Summary

Update module to provide additional built-in values for the template file variables,

## This PR fixes/adds/changes/removes

1. Fixes #255
1. Contributes towards a fix for #207
1. Adds the following key/value pairs to the built-in `template_file_variables` for use with `templatefile()` function when loading templates from the lib folders:

| Source module | Variable name | Example value | Description |
| --- | --- | --- | --- |
| connectivity | `ddos_protection_plan_resource_id` | `/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myorg-ddos/providers/Microsoft.Network/ddosProtectionPlans/myorg-ddos-westus` | Resource ID for the DDoS protection plan created by the module. |
| connectivity | `private_dns_zone_prefix` | `/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myorg-dns/providers/Microsoft.Network/privateDnsZones/` | Resource ID suffix used for all azurerm_private_dns_zone resources created by the module under the scope of connectivity resources. |
| connectivity | `connectivity_location` | `westus` | Location set for the connectivity resources. |
| connectivity | `virtual_network_resource_id_by_location` | `{ westus = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myorg-connectivity-westus/providers/Microsoft.Network/virtualNetworks/myorg-hub-northeurope" }` | Map of Resource IDs by location for virtual network resources created by the module. |
| connectivity | `vpn_gateway_resource_id_by_location` | `{ westus = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myorg-connectivity-westus/providers/Microsoft.Network/virtualNetworkGateways/myorg-vpngw-northeurope" }` | Map of Resource IDs by location for VPN gateway resources created by the module. |
| connectivity | `firewall_resource_id_by_location` | `{ westus = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myorg-connectivity-westus/providers/Microsoft.Network/azureFirewalls/myorg-fw-northeurope" }` | Map of Resource IDs by location for Azure Firewall resources created by the module. |
| management | `log_analytics_workspace_resource_id` | `/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myorg-mgmt/providers/Microsoft.OperationalInsights/workspaces/myorg-la` | Resource ID for the Log Analytics workspace created by the module. |
| management | `log_analytics_workspace_name` | `myorg-la` | Name for the Log Analytics workspace created by the module.
| management | `log_analytics_workspace_location` | `northeurope` | Location for the Log Analytics workspace created by the module. |
| management | `automation_account_resource_id` | `/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myorg-mgmt/providers/Microsoft.Automation/automationAccounts/myorg-automation` | Resource ID for the Automation Account created by the module. |
| management | `automation_account_name` | `myorg-automation` | Name for the Automation Account created by the module.
| management | `automation_account_location` | `northeurope` | Location for the Automation Account created by the module. |
| management | `management_location` | `northeurope` | Location set for the management resources. |
| management | `management_resource_group_name` | `myorg-mgmt` | Name of the Resource Group deployed by the module for management resources. |
| management | `data_retention` | `30` | Retention period (in days) used when configuring the Log Analytics workstation and associated policies. |

### Breaking Changes

*none*

## Testing Evidence

Temporary output was used to validate that values were correctly added to the internal `template_file_variables` object:

image

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.
- [x] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located in the [Enterprise-Scale repo](https://github.com/Azure/Enterprise-Scale) in the directory: `/docs/wiki/whats-new.md`)

### CODE REVIEW

**Review by jtracey93 — DISMISSED** [review]

**Review by matt-FFFFFF — APPROVED** [review]
lgtm :shipit:

**Review by jtracey93 — APPROVED** [review]

**Review by jtracey93 — APPROVED** [review]

**Pull request merged**
