### PR TITLE
Refactor tests

### PR DESCRIPTION
**Pull request by krowlandson**
## Overview/Summary

This PR includes updates to the test framework to provide improved coverage for Virtual WAN connectivity.

## This PR fixes/adds/changes/removes

1. Update test framework to multi-stage deployment
2. Add VWAN testing

### Breaking Changes

*none*

## Testing Evidence

Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

## As part of this Pull Request I have

- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pulls)
- [ ] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues), for tracking and closure.
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main)
- [ ] Performed testing and provided evidence.
- [ ] Updated relevant and associated documentation.
- [ ] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located in the [Enterprise-Scale repo](https://github.com/Azure/Enterprise-Scale) in the directory: `/docs/wiki/whats-new.md`)

### CODE REVIEW

**Comment by krowlandson** [comment]
@jtracey93 @matt-FFFFFF... any thoughts on this PR before I merge into the `vwan` branch? Next update on `vwan` will be Wiki docs updates, then I think we can raise the PR from `vwan` to `main` ready for release `v1.2.0`.

**Review by matt-FFFFFF — APPROVED** [review]

**Pull request merged**
