### PR TITLE
Add ability to disable non-compliance messages and standardise variable naming

### PR DESCRIPTION
**Pull request by jaredfholgate**
## Overview/Summary

This PR is an amendment to the previously merged PR https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pull/601. It adds the ability to turn off the non-compliance message functionality altogether for those that would prefer not to use it.

It also updates the inconsistent naming to use `non_compliance` as opposed to just `compliance` which is not accurate.

## This PR fixes/adds/changes/removes

N/A

### Breaking Changes

None

## Testing Evidence

Portion of plan with default `true` value:

image

Portion of plan with `false` set:

image

image

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.
- [x] Updated the ["RELEASE"](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues) page with details needed for when this code change is released.

### CODE REVIEW

**Comment by jaredfholgate** [comment]
@matt-FFFFFF, @jtracey93 and @krowlandson this is now ready to review.

**Review by krowlandson — COMMENTED** [review]
Love the update to "non-compliance". Great update before we release!

I missed this on the previous review, but we have a pattern where I only reference input variables once (within `locals.tf`) so if we need to make a transformation, validation, or set the value based on a condition, we only have one place to do it. This reduces the risk of inconsistent values then being used somewhere else within the module code.

I realise this potentially has limited value and isn't a "regular" TF standard, but is it worth using this PR to update these to follow the same pattern?

Also, are we able to provide test coverage for this new input?

**Comment by matt-FFFFFF** [comment]
thanks @jaredfholgate looks good will run tests

**Comment by jaredfholgate** [comment]
> Love the update to "non-compliance". Great update before we release!
> 
> I missed this on the previous review, but we have a pattern where I only reference input variables once (within `locals.tf`) so if we need to make a transformation, validation, or set the value based on a condition, we only have one place to do it. This reduces the risk of inconsistent values then being used somewhere else within the module code.
> 
> I realise this potentially has limited value and isn't a "regular" TF standard, but is it worth using this PR to update these to follow the same pattern?
> 
> Also, are we able to provide test coverage for this new input?

I have refactored the vars.

I did have a think about test coverage, but it competes with the last test and we only have 3 tests, so can't add this without invalidating the default text test.

**Review by matt-FFFFFF — APPROVED** [review]

**Comment by matt-FFFFFF** [comment]
thanks @jaredfholgate great work

**Pull request merged**
