### PR TITLE
feat: add container insights option

### PR DESCRIPTION
**Pull request by steph409**
## Feature proposal - add option to add container insights

Similar to vm insights, we should also be able to deploy:

`resource "azurerm_log_analytics_solution" "management"
---

plan {
          + name      = (known after apply)
          + product   = "OMSGallery/ContainerInsights"
          + publisher = "Microsoft"
        }

`

## This PR fixes/adds/changes/removes

no fixes, no changes, no removes. 

this pr adds one resource, which deploys the container insights log analytics solution. 
moreover, it is possible to not deploy this resource, similar to the vm_insights resource. 

### Breaking Changes

None

## Testing Evidence

Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

I tested it locally, works as expected.

## As part of this Pull Request I have

- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pulls)
- [ ] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues), for tracking and closure.
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main)
- [ ] Performed testing and provided evidence.
- [ ] Updated relevant and associated documentation.

### CODE REVIEW

**Review by matt-FFFFFF — CHANGES_REQUESTED** [review]
Thanks for this contribution @steph409 

Please can you add the variable to the parent module. At the moment this works due to the optional function, but we should make it explicit. Thanks

**Comment by steph409** [comment]
Hi @matt-FFFFFF,

thanks for reviewing. I just updated the PR. 

cheers

**Pull request merged**
