### PR TITLE
Removed deprecation warnings regarding network policies

### LINKED ISSUE #445: azurerm v4 compatibility
<h3 id=communitynote>Community Note </h3>
<ul>
<li>Please vote on this issue by adding a &#128077; <a href="https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/">reaction</a> to the original issue to help the community and maintainers prioritize this request </li>
<li>Please do not leave &quot;+1&quot; or &quot;me too&quot; comments, they generate extra noise for issue followers and do not help prioritize the request </li>
<li>If you are interested in working on this issue or have submitted a pull request, please leave a comment </li>
</ul>
<h3 id=versions>Versions </h3>
<p><strong>terraform</strong>: 1.2.x </p>
<p><strong>azure provider</strong>: 3.x </p>
<p><strong>module</strong>: 2.3.1 </p>
<h3 id=description>Description </h3>
<h4 id=describethebug>Describe the bug </h4>
<p>AzureRM provider v4 is making changes and has deprecation warnings: </p>
<pre><code class="text language-text">│ Warning: Argument is deprecated
│ 
│   with module.alz.azurerm_subnet.connectivity,
│   on .terraform/modules/alz/resources.connectivity.tf line 58, in resource &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;azurerm_subnet&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot; &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;connectivity&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;quot;:
│   58:   enforce_private_link_endpoint_network_policies = each.value.template.enforce_private_link_endpoint_network_policies
│ 
│ `enforce_private_link_endpoint_network_policies` will be
│ removed in favour of the property
│ `private_endpoint_network_policies_enabled` in version 4.0
│ of the AzureRM Provider
│ 
│ (and one more similar warning elsewhere)
</code></pre>
<h4 id=stepstoreproduce>Steps to Reproduce</h4>
<ol>
<li>Deploy module with default configuration</li>
</ol>
<h4 id=screenshots>Screenshots</h4>
<p></p>
<h4 id=additionalcontext>Additional context</h4>

### PR DESCRIPTION
**Pull request by jwueste**
## Overview/Summary

This PR removes deprecation warnings regarding network policies, introduced in provider version 3.18.0.

## This PR fixes/adds/changes/removes

resolves #445 

### Breaking Changes

1. enforce_private_link_endpoint_network_policies is replaced by private_endpoint_network_policies_enabled
2. enforce_private_link_service_network_policies is replaced by private_link_service_network_policies_enabled

## As part of this Pull Request I have

- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pulls)
- [X] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues), for tracking and closure.
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main)

### CODE REVIEW

**Comment by krowlandson** [comment]
Thank you for this PR @jwueste 💯 

Please can you link to issue #445?

Also, please can you ensure all documentation is updated to reflect this change before I complete a formal review?

**Comment by jwueste** [comment]
Linking to issue #445 is done. Sorry, forgot keyword...
I could not find any documentation regarding this feature.

**Comment by krowlandson** [comment]
> Linking to issue #445 is done. Sorry, forgot keyword...

Yes, sorry that's what I meant

> I could not find any documentation regarding this feature.

Great, thank you for checking 👍🏻 

I'll take a look and run some checks on the implications of including this with the next release. I suspect very few (if any) customers will be impacted by this beyond the provider update so should be reasonably safe to release as a minor with a clear warning in the release notes. But this is what I need to verify.

Thank you again for your contribution 💯 🏅

**Comment by krowlandson** [comment]
@jwueste ... sorry, just re-engaging my 🧠 ... we will need to update all of the examples and pre-req guidance to reflect the updated minimum supported provider version.

**Comment by krowlandson** [comment]
@jwueste we also need to update the test matrix to reflect the minimum support version here:

https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/31b4391c9d43e3e8ccbdb994dd7e2a7e59388fdc/tests/scripts/azp-strategy.ps1#L54-L61

**Review by krowlandson — APPROVED** [review]
LGTM 🚀

**Comment by krowlandson** [comment]
Awesome stuff @jwueste ... thank you for the contribution 😄

**Pull request merged**
