### PR TITLE
updating threat intelligence allowlist dynamic block

### PR DESCRIPTION
**Pull request by cndaan**
## Overview/Summary

Updating threat intelligence allowlist dynamic block for the hub spoke configuration. Copied the code from the vwan configuration, that seems to work. 

## This PR fixes/adds/changes/removes

1. Now able to update allowlist for threat intelligence in combnation with hub spoke model.
2. Solves issue #949 

## Testing evidence

When adding the fqdns or ip_addresses inside the threat_intelligence_allowlist for the firewall resource,I get the following errors:
image

After the fix the values are added:
image

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main)
- [x] Performed testing and provided evidence.
- [ ] Updated relevant and associated documentation.

### CODE REVIEW

**Review by jordyvpaassen — APPROVED** [review]
approve this code

**Comment by matt-FFFFFF** [comment]
Hi thanks for this PR I will get the tests running

**Review by matt-FFFFFF — APPROVED** [review]

**Comment by matt-FFFFFF** [comment]
We are preparing for the next major release, I will pull this into main and fix forward.

**Pull request merged**
