### PR TITLE
Remove Basic SKU requirement on AzureFirewallManagementSubnet

### PR DESCRIPTION
**Pull request by ryan-royals**
## Overview/Summary

Currently it is required for the Azure Firewall to be Basic SKU for the module to provision the `AzureFirewallManagementSubnet`, but this is not a requirement on the resource itself.

## Testing Evidence
image

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.

### CODE REVIEW

**Comment by matt-FFFFFF** [comment]
@luke-taylor please can you have a a look at this PR - I think it looks good but as you did this work wanted your opinion please :)

**Comment by luke-taylor** [comment]
@ryan-royals The management nic was and still is a requirement for the Basic SKU as far as I can tell. See [here](https://learn.microsoft.com/en-us/azure/firewall/deploy-firewall-basic-portal-policy) 

Please share any evidence of the contrary.

**Comment by luke-taylor** [comment]
LGTM

**Review by luke-taylor — APPROVED** [review]

**Pull request merged**
